### ISSUE TITLE
Save mass based on full volume

### ISSUE THREAD

**Issue by TwistedTail** [DaDamRival/proper_clipping#18]
Something I noticed was that props would slowly become lighter as they got duped. The probable reason is that visclipped entities are saving their actual mass, even if they were physically cut.

https://github.com/DaDamRival/proper_clipping/blob/f8f7ecdee62adaf271b92c87e9110424c3bb437a/lua/autorun/server/proper_clipping.lua#L134-L138

It'd be totally possible to save the real volume at some point before the entity is physically cut and use that as a multiplier for the mass that'd get saved on the entity later on.

https://github.com/DaDamRival/proper_clipping/blob/1eca06cf204503a8e83b996779860fdcddd784d6/lua/autorun/proper_clipping.lua#L148

**Comment by TwistedTail** [comment]
It'd be a good idea to hijack `duplicator.StoreEntityModifier` to apply that multiplier whenever the `mass` entity modifier is stored on the entity.

**Comment by Sevii77** [comment]
I'm unable to reproduce this with both vanilla duplicator and advanced duplicator 2. The mass stays the same and doesn't seem to change. Also applying the multiplier whenever the `mass` entity modifier is stored would be a terrible idea since if the mass were to be set with the weight tool the resulting stored mass would be different from the set mass.
